In [1]:
# ARITMETIC OPERATORS : + , - , * , / , // , % , ** .
# USING add() FUNCTION .

import numpy as np
a = np.array([10,20,30,40,50,60])
b = np.array([16,32,48,64,80,96])
xyz = np.add(a,b)
print(xyz)

[ 26  52  78 104 130 156]


In [2]:
# USING subtract() FUNCTION .

import numpy as np
a = np.array([10,20,30,40,50,60])
b = np.array([16,32,48,64,80,96])
xyz = np.subtract(a,b)
print(xyz)

[ -6 -12 -18 -24 -30 -36]


In [3]:
import numpy as np
a = np.array([10,20,30,40,50,60])
b = np.array([16,32,48,64,80,96])
xyz = np.subtract(b,a)
print(xyz)

[ 6 12 18 24 30 36]


In [4]:
# USING multiply() FUNCTION .

import numpy as np
a = np.array([10,20,30,40,50,60])
b = np.array([16,32,48,64,80,96])
xyz = np.multiply(a,b)
print(xyz)

[ 160  640 1440 2560 4000 5760]


In [5]:
# USING divide() FUNCTION .

import numpy as np
a = np.array([10,20,30,40,50,60])
b = np.array([16,32,48,64,80,96])
xyz = np.divide(a,b)
print(xyz)

[0.625 0.625 0.625 0.625 0.625 0.625]


In [6]:
import numpy as np
a = np.array([10,20,30,40,50,60])
b = np.array([16,32,48,64,80,96])
xyz = np.divide(b,a)
print(xyz)

[1.6 1.6 1.6 1.6 1.6 1.6]


In [7]:
''' 
power() RAISES THE VALUE FROM THE 1ST ARRAY TO THE POWER 
OF THE VALUES OF THE 2ND ARRAY AND RETURN RESULTS IN A NEW ARRAY .
'''

# USING power() FUNCTION .

import numpy as np
c = np.array([6,4,8,5,3,7])
d = np.array([6,7,3,5,8,4])
xyz = np.power(c,d)
print(xyz)

[46656 16384   512  3125  6561  2401]


In [8]:
''' 
mod() AND remainder() RETURNS THE REMAINDER OF THE 1ST ARRAY CORRESPONDING 
TO THE 2ND ARRAY AND RESULT IN THE NEW ARRAY .
'''

# USING mod() FUNCTION .

import numpy as np
e = np.array([52,56,60,64,68,72])
f = np.array([5,6,8,3,7,4])
xyz = np.mod(e,f)
print(xyz)

[2 2 4 1 5 0]


In [9]:
import numpy as np
e = np.array([52,56,60,64,68,72])
f = np.array([5,6,8,3,7,4])
xyz = np.mod(f,e)
print(xyz)

[5 6 8 3 7 4]


In [10]:
# USING remainder() FUNCTION .

import numpy as np
e = np.array([52,56,60,64,68,72])
f = np.array([5,6,8,3,7,4])
xyz = np.remainder(e,f)
print(xyz)

[2 2 4 1 5 0]


In [11]:
import numpy as np
e = np.array([52,56,60,64,68,72])
f = np.array([5,6,8,3,7,4])
xyz = np.remainder(f,e)
print(xyz)

[5 6 8 3 7 4]


In [12]:
# divmod() RETURNS BOTH THE QUOTIENT AND THE REMAINDER .
# USING divmod() FUNCTION .

import numpy as np
e = np.array([52,56,60,64,68,72])
f = np.array([5,6,8,3,7,4])
xyz = np.divmod(e,f)
print(xyz)

(array([10,  9,  7, 21,  9, 18]), array([2, 2, 4, 1, 5, 0]))


In [13]:
''' 
absolute() AND abs() DO THE SAME OPERATION BUT IN ufunc() USE THE absolute() TO AVOID
CONFUSION WITH PYTHON IN BUILT FUNCTION math.abs() .
'''

# USING absolute() FUNCTION .

import numpy as np
g = np.array([-12,-8,-4,0,4,8])
xyz = np.absolute(g)
print(xyz)

[12  8  4  0  4  8]


In [14]:
# USING abs() FUNCTION .

import numpy as np
g = np.array([-12,-8,-4,0,4,8])
xyz = np.abs(g)
print(xyz)

[12  8  4  0  4  8]
