In [1]:
# SLICING ARRAYS : SLICING IN PYHTON MEANS TAKING ELEMENTS FORM ONE GIVEN INDEX TO ANOTHER INDEX .
# SLICING FORMAT : [START:END] , [START:END:STEP]

import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a[1:5])

[2 3 4 5]


In [2]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a[4:])

[ 5  6  7  8  9 10]


In [3]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a[:4])

[1 2 3 4]


In [4]:
# NEGATIVE SLICING 

a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a[-6:-1])

[5 6 7 8 9]


In [5]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a[-3:-1])

[8 9]


In [6]:
# STEP VALUE : IT IS USED TO DETERMINE THE STEP OF THE SLICING .

b = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print(b[0:20:4])

[ 1  5  9 13 17]


In [7]:
b = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print(b[::4])

[ 1  5  9 13 17]


In [8]:
b = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print(b[10::2])

[11 13 15 17 19]


In [9]:
b = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print(b[:10:2])

[1 3 5 7 9]


In [10]:
# SLICING TWO DIMENSIONAL ARRAY : PRINT 7 8 9 .

c = np.array ([ [1,2,3,4,5] , [6,7,8,9,10] ])
print (c[1,1:4])

[7 8 9]


In [11]:
# PRINT FROM BOTH THE INDEX VALUE 2 .

c = np.array ([ [1,2,3,4,5] , [6,7,8,9,10] ])
print(c[0:2,2])

[3 8]


In [12]:
# PRINT FROM BOTH INDEX 1 TO INDEX 4 .

c = np.array ([ [1,2,3,4,5] , [6,7,8,9,10] ])
print(c[0:2,1:4])

[[2 3 4]
 [7 8 9]]
