In [1]:
# GETTING SOME ELEMENTS OUT OF AN EXISTING ARRAY AND CREATING A NEW ARRAY IS CALLED FILTERING .
# A BOOLEAN INDEX LIST IS A LIST OF BOOLEAN CORRESPONDING TO INDEXES IN THE ARRAY .
# A BOOLEAN LIST CONSISTS OF True AND False ONLY .
# CREATE AN ARRAY FROM BOOLEAN INDEX LIST .

import numpy as np
a = np.array([11,12,13,14,15,16,17,18,19,20])
b = [ True , False , True , False , True , False , True , False , True , False ]
c = a[b]
print(c)

[11 13 15 17 19]


In [2]:
# CREATE AN ARRAY CONTAING VALUES GREATER THAN 5 FROM 1 TO 10 .

d = np.array([1,2,3,4,5,6,7,8,9,10])
e = []

for xx in d:
    if xx > 5:
        e.append(True)
    else:
        e.append(False)

f = d[e]
print(e)
print(f)

[False, False, False, False, False, True, True, True, True, True]
[ 6  7  8  9 10]


In [3]:
# CREATE AN ARRAY CONTAING EVEN VALUES FROM 21 TO 30 .

g = np.array([21,22,23,24,25,26,27,28,29,30])
h = []

for yy in g:
    if yy % 2 == 0:
        h.append(True)
    else:
        h.append(False)
        
k = g[h]
print(h)
print(k)

[False, True, False, True, False, True, False, True, False, True]
[22 24 26 28 30]


In [4]:
# CREATE FILTER DIRECTLY FROM AN ARRAY .
# CREATE AN ARRAY CONTAING VALUES GREATER THAN 5 FROM 1 TO 10 .

d = np.array([1,2,3,4,5,6,7,8,9,10])
e = d > 5 
f = d[e]
print(e)
print(f)

[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]


In [5]:
# CREATE FILTER DIRECTLY FROM AN ARRAY .
# CREATE AN ARRAY CONTAING EVEN VALUES FROM 21 TO 30 .

g = np.array([21,22,23,24,25,26,27,28,29,30])
h = g % 2 == 0
k = g[h]
print(h)
print(k)

[False  True False  True False  True False  True False  True]
[22 24 26 28 30]
