In [1]:
# RESHAPING MEANS CHANGING THE SHAPE OF AN ARRAY LIKE ADDING OR REMOVING THE ELEMENTS .
# RESHAPING ARRAY FROM ONE DIMENSIONAL TO TWO DIMENSIONAL .

import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
b = a.reshape(4,3)
print(b)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [2]:
# RESHAPING ARRAY FROM ONE DIMENSIONAL TO THREE DIMENSIONAL .

a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
c = a.reshape(2,3,2)
print(c)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [3]:
# RETURN VIEW 

a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
c = a.reshape(2,3,2).base
print(c)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [4]:
# WE ARE ALLOWED TO HAVE ONLY ONE UNKOWN DIMENSION .
# FOR UNKOWN DIMENSION WE PASS "-1" .

a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
d = a.reshape(2,2,-1)
print(d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [5]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
e = a.reshape(2,-1,2)
print(e)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [6]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
f = a.reshape(-1,2,3)
print(f)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [7]:
# FLATTENING THE ARRAY BY CONVERTING MULTI-DIMENSIONAL ARRAY TO ONE DIMENSIONAL ARRAY .

g = np.array ([ [1,2,3,4] , [5,6,7,8] ])
h = g.reshape(-1)
print(h)

''' 
THERE ARE A LOT OF FUNCTIONS FOR CHANGING THE SHAPE OF AN ARRAY IN NUMPY LIKE 
FLATTERN , RAVEL , REARRANGE , ROT90 , FLIP , FLIPLR , FLIPUD . 
THEY ARE ALL ACTUALLY COMES UNDER ADVANCE NUMPY . 
'''

[1 2 3 4 5 6 7 8]


' \nTHERE ARE A LOT OF FUNCTIONS FOR CHANGING THE SHAPE OF AN ARRAY IN NUMPY LIKE \nFLATTERN , RAVEL , REARRANGE , ROT90 , FLIP , FLIPLR , FLIPUD . \nTHEY ARE ALL ACTUALLY COMES UNDER ADVANCE NUMPY . \n'