In [1]:
# SHAPE OF ARRAY : IT IS THE NUMBER OF ELEMENTS IN EACH DIMENSIONS .

import numpy as np
a = np.array ([ [1,2,3,4] , [5,6,7,8] ])
print(a)
print ( "THE SHAPE OF ARRAY :" , a.shape )

# SHAPE (2,4) WHICH MEANS ARRAY HAS 2 DIMENSIONS AND ARRAY HAS 4 ELEMENTS .

[[1 2 3 4]
 [5 6 7 8]]
THE SHAPE OF ARRAY : (2, 4)


In [2]:
# CREATE FIVE DIMENSIONAL ARRAY USING ndmin() .

b = np.array ( [1,2,3,4] , ndmin=5 )
print(b)
print ( "THE SHAPE OF ARRAY :" , b.shape )

[[[[[1 2 3 4]]]]]
THE SHAPE OF ARRAY : (1, 1, 1, 1, 4)


In [3]:
# CREATE SIX DIMENSIONAL ARRAY USING ndmin() .

c = np.array ( [ [1,2,3] , [4,5,6] ] , ndmin=6 )
print(c)
print ( "THE SHAPE OF ARRAY :" , c.shape )

[[[[[[1 2 3]
     [4 5 6]]]]]]
THE SHAPE OF ARRAY : (1, 1, 1, 1, 2, 3)
