In [1]:
# JOINING ONE DIMENSIONAL ARRAYS USING concatenate() .

import numpy as np
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
a3 = np.concatenate ((a1,a2))
print(a3)

[1 2 3 4 5 6]


In [2]:
b1 = np.array ([ "LIMA" , "OTTAWA" , "BOGOTA" , "HAVANA" , "QUITO" , "SANTIAGO" ])
b2 = np.array ([  "KINGSTON" , "CARACAS" , "BELMOPAN" , "GEORGETOWN" , "BRASILIA" , "BRIDGETOWN" ])
b3 = np.concatenate ((b1,b2))
print(b3)

['LIMA' 'OTTAWA' 'BOGOTA' 'HAVANA' 'QUITO' 'SANTIAGO' 'KINGSTON' 'CARACAS'
 'BELMOPAN' 'GEORGETOWN' 'BRASILIA' 'BRIDGETOWN']


In [3]:
# JOINING TWO DIMENSIONAL ARRAYS ALONG THE ROWS USING concatenate() .
# ALONG THE ROWS MEANS axis = 1 .

c1 = np.array ([ [1,2] , [3,4] ])
c2 = np.array ([ [5,6] , [7,8] ])
c3 = np.concatenate ( (c1,c2) , axis=1 )
print(c3)

[[1 2 5 6]
 [3 4 7 8]]


In [4]:
# JOINING ONE DIMENSIONAL ARRAYS USING stack() .

a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
a3 = np.stack ( (a1,a2) , axis=1 )
print(a3)

[[1 4]
 [2 5]
 [3 6]]


In [5]:
# JOINING ONE DIMENSIONAL ARRAYS USING hstack() .
# hstack() MEANS STACKING ALONG THE ROW .

a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
a3 = np.hstack ((a1,a2))
print(a3)

[1 2 3 4 5 6]


In [6]:
# JOINING ONE DIMENSIONAL ARRAYS USING vstack() .
# vstack() MEANS STACKING ALONG THE COLUMN .

a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
a3 = np.vstack ((a1,a2))
print(a3)

[[1 2 3]
 [4 5 6]]


In [7]:
# JOINING ONE DIMENSIONAL ARRAYS USING dstack() .
# dstack() MEANS STACKING ALONG THE HEIGHT OR DEPTH .

a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
a3 = np.dstack ((a1,a2))
print(a3)

[[[1 4]
  [2 5]
  [3 6]]]
