In [1]:
# TO SEARCH AN ARRAY FOR A CERTAIN VALUE AND RETURN THE INDEXES THAT GET THE MATCH USING where() .

import numpy as np
a1 = np.array ([16,14,18,20,16,12,14,18,14,12,20,14])
a2 = np.where ( a1 == 14 )
print(a2)

(array([ 1,  6,  8, 11], dtype=int64),)


In [2]:
# FIND THE INDEXES WHERE VALUES ARE EVEN .

b1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
b2 = np.where ( b1 % 2 == 0 )
print(b2)

(array([ 1,  3,  5,  7,  9, 11], dtype=int64),)


In [3]:
b1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
b2 = np.where ( b1 % 2 != 1 )
print(b2)

(array([ 1,  3,  5,  7,  9, 11], dtype=int64),)


In [4]:
# FIND THE INDEXES WHERE VALUES ARE ODD .

b1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
b2 = np.where ( b1 % 2 == 1 )
print(b2)

(array([ 0,  2,  4,  6,  8, 10], dtype=int64),)


In [5]:
b1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
b2 = np.where ( b1 % 2 != 0 )
print(b2)

(array([ 0,  2,  4,  6,  8, 10], dtype=int64),)


In [6]:
# searchsorted() IS USED TO PERFORM BINARY SEARCH IN ARRAY .
# FIND THE INDEX WHERE VALUE 40 IS INSERTED .

c1 = np.array([32,34,36,38,40,42,44,46,48,50])
c2 = np.searchsorted ( c1 , 40 )
print(c2)

4


In [7]:
# FIND THE INDEX WHERE VALUE 40 IS INSERTED FROM LEFT SIDE .

c1 = np.array([32,34,36,38,40,42,44,46,48,50])
c2 = np.searchsorted ( c1 , 40 , side="left" )
print(c2)

4


In [8]:
# FIND THE INDEX WHERE VALUE 40 IS INSERTED FROM RIGHT SIDE .

c1 = np.array([32,34,36,38,40,42,44,46,48,50])
c2 = np.searchsorted ( c1 , 40 , side="right" )
print(c2)

5


In [9]:
# SEARCHING MULTIPLE VALUES IN AN ARRAY .

d1 = np.array([16,13,19,18,11,15,14,20,12,17])
d2 = np.searchsorted ( d1 , [16,12,18,14] )
print(d2)

[ 9  0 10  2]


In [10]:
d1 = np.array([16,13,19,18,11,15,14,20,12,17])
d2 = np.searchsorted ( d1 , [23,21,24,22] )
print(d2)

[10 10 10 10]


In [11]:
d1 = np.array([16,13,19,18,11,15,14,20,12,17])
d2 = np.searchsorted ( d1 , [6,2,8,4] )
print(d2)

[0 0 0 0]
