In [1]:
# THE ARRAY OBJECT IN NUMPY IS CALLED NDARRAY .

import numpy as np
a = np.array([1,2,3,4,5,6])
print(a)


[1 2 3 4 5 6]


In [2]:
# WE CAN ALSO PASS A LIST , TUPLE OR ANY ARRAY LIKE OBJECT WITH array() . ALL WILL BE ONVERTED TO NDARRAY .

b = np.array((11,12,13,14,15,16))
print(b)
print(type(b))

[11 12 13 14 15 16]
<class 'numpy.ndarray'>


In [3]:
# DIMENSIONS IN ARRAY : IT IS ONE LEVEL OF ARRAY DEPTH ALSO KNOWN AS NESTED ARRAY .
# ZERO DIMENSIONAL ARRAY OR SCALARS ARE THE ELEMENTS IN AN ARRAY .
# EACH VALUE IN AN ARRAY IS ZERO DIMENSIONAL .

c = np.array(64)
print(c)
print(type(c))

64
<class 'numpy.ndarray'>


In [4]:
# ONE DIMESNIONAL ARRAY OR UNI DIRECTIONAL ARRAY THAT HAS ZERO DIMENSIONAL ARRAY AS ITS ELEMENTS .

d = np.array([21,22,23,24,25,26])
print(d)

[21 22 23 24 25 26]


In [5]:
# TWO DIMESNIONAL ARRAY :

e = np.array ( [ [1,2,3,4] , [5,6,7,8] ] )
print(e)

[[1 2 3 4]
 [5 6 7 8]]


In [6]:
# THREE DIMESNIONAL ARRAY :

f = np.array ( [ [ [31,32] , [33,34] ] , [ [35,36], [37,38] ] ] )
print(f)

[[[31 32]
  [33 34]]

 [[35 36]
  [37 38]]]


In [7]:
# ndim ATTRIBUTE USED TO CHECK THE NUMBER OF DIMENSIONS IN AN ARRAY .

c = np.array(64)
d = np.array([21,22,23,24,25,26])
e = np.array ( [ [1,2,3,4] , [5,6,7,8] ] )
f = np.array ( [ [ [31,32] , [33,34] ] , [ [35,36], [37,38] ] ] )

print(c.ndim)
print(d.ndim)
print(e.ndim)
print(f.ndim)

0
1
2
3


In [8]:
# CREATE AN ARRAY WITH FIVE DIMENSIONS AND VERIFY THAT IT HAS FIVE DIMENSIONS .

g = np.array ( [1,2,3,4] , ndmin = 5 )
print(g)
print ( "THE NUMBERS OF DIMENSIONS :" , g.ndim )

[[[[[1 2 3 4]]]]]
THE NUMBERS OF DIMENSIONS : 5
