In [1]:
# sort() IS USED TO SORT OR ORDER A SPECIFIED ARRAY .
# ORDER CAN DONE BE IN ASCENDING OR DESCENDING WAY .
# SORT THE ARRAY NUMERICALLY .

import numpy as np
a1 = np.array([38,44,34,40,48,36,50,32,42,46])
a2 = np.sort(a1)
print(a2)

# sort() IS SOME WHAT LIKE AS copy() .

[32 34 36 38 40 42 44 46 48 50]


In [2]:
# SORT THE ARRAY ALPHABETICALLY .

b1 = np.array ([ "LEO"  , "BEN" , "VAN" , "ACE" , "RIO" , "TOM" , "JIM" , "DAX" , "FOX" , "OAK" ])
b2 = np.sort(b1)
print(b2)

['ACE' 'BEN' 'DAX' 'FOX' 'JIM' 'LEO' 'OAK' 'RIO' 'TOM' 'VAN']


In [3]:
# SORT THE BOOLEAN ARRAY .

c1 = np.array ([ True , False , True , False , True , False ])
c2 = np.sort(c1)
print(c2)

[False False False  True  True  True]


In [4]:
# SORT THE TWO DIMENSIONAL ARRAY .

d1 = np.array ([ [34,32,35,31,33] , [38,39,36,40,37] , [43,45,41,42,44] , [48,46,50,47,49]  ])
d2 = np.sort(d1)
print(d2)

[[31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]


In [5]:
e1 = np.array ([ "LEO"  , "BEN" , "VAN" , "ACE" , "RIO" , "TOM" , "JIM" , "DAX" , "FOX" , "OAK" , 
                6 , 8 , 3 , 10 , 1 , 7 , 2 , 9 , 5 , 4 ])
e2 = np.sort(e1)
print(e2)

['1' '10' '2' '3' '4' '5' '6' '7' '8' '9' 'ACE' 'BEN' 'DAX' 'FOX' 'JIM'
 'LEO' 'OAK' 'RIO' 'TOM' 'VAN']
