In [1]:
# COPY ARRAY 

import numpy as np
a1 = np.array([42,28,24,32,26,30,40,34])
a2 = a1.copy()
print(a1)
print(a2)

[42 28 24 32 26 30 40 34]
[42 28 24 32 26 30 40 34]


In [2]:
import numpy as np
a1 = np.array([42,28,24,32,26,30,40,34])
a2 = a1.copy()
a1[0] = 38
print(a1)
print(a2)

[38 28 24 32 26 30 40 34]
[42 28 24 32 26 30 40 34]


In [3]:
import numpy as np
a1 = np.array([42,28,24,32,26,30,40,34])
a2 = a1.copy()
a2[0] = 38
print(a1)
print(a2)

[42 28 24 32 26 30 40 34]
[38 28 24 32 26 30 40 34]


In [4]:
# VIEW ARRAY

import numpy as np
b1 = np.array([42,28,24,32,26,30,40,34])
b2 = b1.view()
print(b1)
print(b2)

[42 28 24 32 26 30 40 34]
[42 28 24 32 26 30 40 34]


In [5]:
import numpy as np
b1 = np.array([42,28,24,32,26,30,40,34])
b2 = b1.view()
b1[0] = 38
print(b1)
print(b2)

[38 28 24 32 26 30 40 34]
[38 28 24 32 26 30 40 34]


In [6]:
import numpy as np
b1 = np.array([42,28,24,32,26,30,40,34])
b2 = b1.view()
b2[0] = 38
print(b1)
print(b2)

[38 28 24 32 26 30 40 34]
[38 28 24 32 26 30 40 34]
