In [1]:
# DATA DISTRIBUTION : IT IS A LIST OF ALL POSSIBLE VALUE AND HOW OFTEN EACH VALUE OCCUR .
# SUCH LIST ARE IMPORTANT WHEN WORKING WITH STATISTICS AND DATA SCIENCE .
# RANDOM DISTRIBUTION IS ALSO KNOWN AS PROBABILITY FUNCTION .


''' 
GENERATE ONE DIMENSIONAL ARRAY WITH 20 VALUES 
WHERE EACH VALUE HAS TO BE 12 , 14 , 16 , 18 , 20 .
THE PROBABILITY FOR THE VALUE 12 IS SET TO BE 0.4
THE PROBABILITY FOR THE VALUE 14 IS SET TO BE 0.3
THE PROBABILITY FOR THE VALUE 16 IS SET TO BE 0.2
THE PROBABILITY FOR THE VALUE 18 IS SET TO BE 0.1
THE PROBABILITY FOR THE VALUE 20 IS SET TO BE 0.0
THE SUM OF ALL PROBABILITY NUMBERS SHOULD BE 1.0 ONLY .
'''

from numpy import random
a = random.choice ( [12,14,16,18,20] , p=[0.4,0.3,0.2,0.1,0.0] , size=(20) )
print(a)

[18 14 12 12 14 12 14 12 12 12 16 16 12 12 18 14 12 14 12 18]


In [2]:
# GENERATE A TWO DIMENSIONAL ARRAY WITH 4 ROWS EACH CONTAING 6 VALUES .

from numpy import random
b = random.choice ( [12,14,16,18,20] , p=[0.4,0.3,0.2,0.1,0.0] , size=(4,6) )
print(b)

[[18 12 16 16 16 14]
 [12 14 16 14 12 14]
 [12 12 18 12 12 16]
 [12 14 18 12 12 12]]
