In [1]:
# DATA TYPES IN PYTHON : STRING , INTEGER , FLOAT , BOOLEAN , COMPLEX .

''' DATA TYPES IN NUMPY :
"i" FOR INTEGER , 
"b" FOR BOOLEAN , 
"u" FOR UNSIGNED INTEGER , 
"f" FOR FLOAT , 
"c" FOR COMPLEX FLOAT , 
"m" FOR TIMEDELTA , "M" FOR DATETIME , 
"O" FOR OBJECT , 
"S" FOR STRING , 
"U" FOR UNICODE STRING ,
"V" FOR MEMORY . '''

# dtype() IS USED TO CHECK THE DATA TYPE OF NUMPY .

import numpy as np
a = np.array([11,12,13,14,15,16])
print(a.dtype)

int32


In [2]:
b = np.array ([ "GERMANY" , "ITALY" , "SPAIN" , "POLAND" , "FRANCE" , "DENMARK" ])
print(b.dtype)

<U7


In [3]:
c = np.array ([ "BANANA" , "MANGO" , "ORANGE" , "APPLE" ])
print(c.dtype)

<U6


In [4]:
# CREATING ARRAY WITH A DEFINED DATA TYPE .

a = np.array ( [11,12,13,14,15,16] , dtype="S" )
print(a)
print(a.dtype)

[b'11' b'12' b'13' b'14' b'15' b'16']
|S2


In [5]:
d = np.array ( [1,2,3,4] , dtype="S" )
print(d)
print(d.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [6]:
# CREATE AN ARRAY WITH INTEGER DATA TYPE OF 4 BYTES .

d = np.array ( [1,2,3,4] , dtype="i4" )
print(d)
print(d.dtype)

[1 2 3 4]
int32


In [7]:
e = np.array ( [1,2,3,4,5,6,7,8] , dtype="i4" )
print(e)
print(e.dtype)

''' IF A TYPE IS GIVEN IN WHICH THE ELEMENTS CANNOT BE CASTED 
THEN NUMPY WILL RAISE ERROR IF VALUE CANNOT BE CONVERTED . '''

[1 2 3 4 5 6 7 8]
int32


' IF A TYPE IS GIVEN IN WHICH THE ELEMENTS CANNOT BE CASTED \nTHEN NUMPY WILL RAISE ERROR IF VALUE CANNOT BE CONVERTED . '

In [8]:
# astype() IS USED TO CONVERT DATA TYPE OF EXISTING ARRAY .
# CONVERTING DATA TYPE FROM FLOAT TO INTEGER .

f1 = np.array ([ 0.8 , 1.6 , 2.4 , 3.2 , 4.0 , 4.8 , 5.6 , 6.4 , 7.2 , 8.0 ])
f2 = f1.astype("i")
print(f2)
print(f2.dtype)

[0 1 2 3 4 4 5 6 7 8]
int32


In [9]:
f1 = np.array ([ 0.8 , 1.6 , 2.4 , 3.2 , 4.0 , 4.8 , 5.6 , 6.4 , 7.2 , 8.0 ])
f2 = f1.astype(int)
print(f2)
print(f2.dtype)

[0 1 2 3 4 4 5 6 7 8]
int32


In [10]:
# CONVERTING DATA TYPE FROM INTEGER TO BOOLEAN .

g1 = np.array ([ 4 , 0 , -8 , 0.0 , 4.8 ])
g2 = g1.astype(bool)
print(g2)
print(g2.dtype)

[ True False  True False  True]
bool
