In [1]:
'''
HYPERBOLIC FUNCTIONS : NUMPY PROVIDES THE ufunc() LIKE sinh() , cosh() , tanh() THAT TAKES VALUES IN RADIANS 
AND PRODUCE THE CORRESPONDING sinh() , cosh() , tanh() VALUES .
'''

# FIND SINH VALUE OF pi/2 .

import numpy as np
a1 = np.sinh(np.pi/2)
print(a1)

2.3012989023072947


In [2]:
# FIND COSH VALUE OF pi/2 .

import numpy as np
a2 = np.cosh(np.pi/2)
print(a2)

2.5091784786580567


In [3]:
# FIND TANH VALUE OF pi/2 .

import numpy as np
a3 = np.tanh(np.pi/2)
print(a3)

0.9171523356672744


In [4]:
# FIND SINH VALUE OF AN ARRAY .

import numpy as np
b1 = np.array ([  np.pi/3 , np.pi/4 , np.pi/5 , np.pi/6 , np.pi/7 , np.pi/8 ])
xyz = np.sinh(b1)
print(xyz)

[1.24936705 0.86867096 0.670484   0.54785347 0.46401763 0.40287038]


In [5]:
# FIND COSH VALUE OF AN ARRAY .

import numpy as np
b2 = np.array ([  np.pi/3 , np.pi/4 , np.pi/5 , np.pi/6 , np.pi/7 , np.pi/8 ])
xyz = np.cosh(b2)
print(xyz)

[1.60028686 1.32460909 1.20397209 1.14023832 1.10241207 1.07810229]


In [6]:
# FIND TANH VALUE OF AN ARRAY .

import numpy as np
b3 = np.array ([  np.pi/3 , np.pi/4 , np.pi/5 , np.pi/6 , np.pi/7 , np.pi/8 ])
xyz = np.tanh(b3)
print(xyz)

[0.78071444 0.6557942  0.55689331 0.48047278 0.42091124 0.37368475]


In [7]:
'''
NUMPY PROVIDES THE ANGLES OF arcsinh() , arccosh() , arctanh() THAT TAKES VALUES IN RADIANS 
AND PRODUCE THE CORRESPONDING sinh() , cosh() , tanh() VALUES .
'''

# FIND ARCSINH ANGLE OF 1.0 .

import numpy as np
c1 = np.arcsinh(1.0)
print(c1)

0.881373587019543


In [8]:
# FIND ARCCOSH ANGLE OF 1.0 .

import numpy as np
c2 = np.arccosh(1.0)
print(c2)

0.0


In [9]:
# FIND ARCTANH ANGLE OF 1.0 .

import numpy as np
c3 = np.arctanh(0.1)
print(c3)

0.1003353477310756


In [10]:
# FIND ARCSINH ANGLE OF AN ARRAY .

import numpy as np
d1 = np.array ([ -0.5 , -0.2 , -0.1 , 0.1 , 0.2 , 0.5 ])
xyz = np.arcsinh(d1)
print(xyz)

[-0.48121183 -0.19869011 -0.09983408  0.09983408  0.19869011  0.48121183]


In [11]:
# FIND ARCCOSH ANGLE OF AN ARRAY .

import numpy as np
d2 = np.array ([ 1.1 , 1.2 , 1.3 , 1.4 , 1.5 , 1.6 ])
xyz = np.arccosh(d2)
print(xyz)

[0.44356825 0.6223625  0.75643291 0.86701473 0.96242365 1.04696792]


In [12]:
# FIND ARCTANH ANGLE OF AN ARRAY .

import numpy as np
d3 = np.array ([ -0.5 , -0.2 , -0.1 , 0.1 , 0.2 , 0.5 ])
xyz = np.arctanh(d3)
print(xyz)

[-0.54930614 -0.20273255 -0.10033535  0.10033535  0.20273255  0.54930614]
