In [1]:
# MULTINOMIAL DISTRIBUION : IT A GENERALIZATION OF BINOMIAL DISTRIBUTION .
# random.multinomial() IS USED FOR MULTINOMIAL DISTRIBUION.

'''
random.multinomial() HAS 3 ARGUMENTS : n() , pvals() , size() .
n() MEANS NUMBER OF POSSIBILITY OR OUTCOME .
pvals() MEANS LIST OF POSSIBILITY OR OUTCOME .
size() MEANS SHAPE OF RETURNED ARRAY .
'''

# GENERATE A MULTINOMIAL DISTRIBUION FOR DICE ROLL OR CUBE SAMPLE .

from numpy import random
a = random.multinomial ( n=6 , pvals=[1/6,1/6,1/6,1/6,1/6,1/6] )
print(a)

[1 3 1 0 1 0]


In [2]:
'''
MULTINOMIAL SAMPLES WILL NOT PRODUCE A SINGLE VALUE . 
THEY WILL PRODUCE ONE VALUE FOR EACH pvals() OR POSSIBILITY .
'''

# GENERATE A MULTINOMIAL DISTRIBUION FOR PYRAMIX SAMPLE .

from numpy import random
b = random.multinomial ( n=4 , pvals=[1/4,1/4,1/4,1/4] )
print(b)

[2 1 1 0]


In [3]:
# GENERATE A MULTINOMIAL DISTRIBUION FOR COIN SAMPLE .

from numpy import random
c = random.multinomial ( n=2 , pvals=[1/2,1/2] )
print(c)

[1 1]


In [4]:
# VISUALIZATION FOR MULTINOMIAL DISTRIBUION .

from numpy import random
import matplotlib.pyplot as plt
import seaborn as sns

a = random.multinomial ( n=6 , pvals=[1/6,1/6,1/6,1/6,1/6,1/6] )
sns.distplot ( a , hist=False )
plt.show()

C:\Users\ARPIT-MIMANI\AppData\Local\Temp\ipykernel_5180\2889467864.py:8: UserWarning: 

`distplot` is a deprecated function and will be removed in seaborn v0.14.0.

Please adapt your code to use either `displot` (a figure-level function with
similar flexibility) or `kdeplot` (an axes-level function for kernel density plots).

For a guide to updating your code to use the new functions, please see
https://gist.github.com/mwaskom/de44147ed2974457ad6372750bbe5751

  sns.distplot ( a , hist=False )


In [5]:
from numpy import random
d = random.multinomial ( n=6 , pvals=[1/3,1/3,1/3,0,0,0] )
print(d)

[3 3 0 0 0 0]
