In [1]:
# PERMUTATION REFERS TO AN ARRANGEMENT OF ELEMENTS .
# EXAMPLE : [1,2,3,4] IS PERMUTATION OF [4,3,2,1] OR VICE VERSA .

# RANDOM MODULE HAS 2 METHODS : permutation() AND shuffle() 
# shuffle() : IT MAKES CHANGES TO THE ORIGINAL ARRAY .

from numpy import random
import numpy as np

a = np.array([11,12,13,14,15,16])
random.shuffle(a)
print(a)

[12 15 14 16 13 11]


In [2]:
from numpy import random
import numpy as np

b = np.array([11,12,12,13,14,14])
random.shuffle(b)
print(b)

[11 14 14 12 13 12]


In [3]:
# permutation() : IT LEAVES THE ORIGINAL ARRAY UNCHANGED .

from numpy import random
import numpy as np

a = np.array([11,12,13,14,15,16])
random.permutation(a)
print(a)

[11 12 13 14 15 16]


In [4]:
from numpy import random
import numpy as np

a = np.array([11,12,13,14,15,16])
x = random.permutation(a)
print(x)

[11 15 14 13 16 12]


In [5]:
from numpy import random
import numpy as np

b = np.array([11,12,12,13,14,14])
y = random.permutation(b)
print(y)

[11 12 14 12 14 13]
