In [1]:
# RANDOM : SOMETHING THAT CANNOT BE PREDICTED LOGICALLY .
# GENERATE A RANDOM INTEGER NUMBER FROM 1 TO 10 .
# randint() IS USED TO GENERATE ONLY RANDOM INTEGER NUMBER .

from numpy import random
a = random.randint(1,11)
print(a)

9


In [2]:
# WE CAN GENERATE float() BY USING rand() 
# rand() GENERATES FLOAT VALUES BETWEEN 0 TO 1 ONLY .

b = random.rand()
print(b)

0.8604255167330371


In [3]:
# GENERATE TWO DIMENSIONAL ARRAY WITH 3 ROWS , EACH ROW CONTAINING 4 RANDOM FLOAT VALUES .

c = random.rand(3,4)
print(c)

[[0.61923185 0.95149988 0.24808447 0.79277509]
 [0.22382611 0.05573975 0.26710868 0.73959469]
 [0.99511816 0.02711368 0.61948346 0.01915696]]


In [4]:
# GENERATE ONE DIMENSIONAL ARRAY CONTAINING 6 RANDOM FLOAT VALUES .

d = random.rand(6)
print(d)

[0.95887345 0.85383094 0.95698661 0.71348195 0.47941973 0.76583581]


In [5]:
# GENERATE ONE DIMENSIONAL ARRAY CONTAINING 6 RANDOM INTEGER VALUES FROM 0 TO 20 .

e = random.randint ( 21 , size=(6) )
print(e)

[19  0  4  2  6 16]


In [6]:
# GENERATE ONE DIMENSIONAL ARRAY CONTAINING 6 RANDOM INTEGER VALUES FROM -10 TO -1 .

f = random.randint ( -10 , 0 , size=(6) )
print(f)

[-9 -5 -4 -4 -7 -2]


In [7]:
# GENERATE TWO DIMENSIONAL ARRAY WITH 6 ROWS , EACH ROW CONTAIN 8 RANDOM INTEGER VALUES FROM 1 TO 40 .

g = random.randint ( 1 , 41 , size=(6,8) )
print(g)

[[40  8 12 32 20 11 36 29]
 [12  1 40 21 40 19 25 22]
 [32 40 14 20 36 20 35 34]
 [ 8 11  5 32 24  5  2  1]
 [13 30 16 20 10 13 20 27]
 [35 30 18 32 12 36 23 26]]


In [8]:
# choice() IS USED TO GENERATE RANDOM NUMBERS FROM AN EXISTING ARRAY .

h = random.choice([38,44,34,48,36,50,42,32,46,40])
print(h)

48


In [9]:
# GENERATE RANDOM NUMBERS FROM ONE DIMENSIONAL ARRAY USING choice() .

k = random.choice ( [38,44,34,48,36,50,42,32,46,40] , size=(6) )
print(k)

[44 40 50 44 42 46]


In [10]:
# GENERATE RANDOM NUMBERS FROM TWO DIMENSIONAL ARRAY USING choice() .

l = random.choice ( [38,44,34,48,36,50,42,32,46,40] , size=(5,6) )
print(l)

[[42 40 38 50 40 32]
 [48 50 40 32 42 38]
 [50 48 46 48 50 34]
 [34 46 36 46 38 32]
 [32 36 32 36 40 44]]
