In [1]:
'''
ROUNDING DECIMALS : THERE ARE 5 WAYS OF ROUNDING DECIMALS .
THEY ARE trunc() , fix() , around() , floor() , ceil() .
'''

# trunc() AND fix() REMOVES THE DECIMALS AND RETURN THE FLOAT NUMBER CLOSEST TO ZERO .
# USING trunc() FUNCTION .

import numpy as np
xyz = np.trunc ([ -8.836 , -5.184 , -4.5 , -3.5 , 1.5 , 2.5 , 6.084 , 7.744 ])
print(xyz)

[-8. -5. -4. -3.  1.  2.  6.  7.]


In [2]:
# USING fix() FUNCTION .

import numpy as np
xyz = np.trunc ([ -8.836 , -5.184 , -4.5 , -3.5 , 1.5 , 2.5 , 6.084 , 7.744 ])
print(xyz)

[-8. -5. -4. -3.  1.  2.  6.  7.]


In [3]:
# around() INCREMENTS PRECEDING DIGIT OR DECIMAL BY NEAREST TO ONE .
# USING around() FUNCTION .

import numpy as np
a = np.around ( -8.836 , 2 )
print(a)

-8.84


In [4]:
import numpy as np
b = np.around ( -5.184 , 2 )
print(b)

-5.18


In [5]:
import numpy as np
c = np.around ( -4.5 , 0 )
print(c)

-4.0


In [6]:
import numpy as np
d = np.around ( -3.5 , 0 )
print(d)

-4.0


In [7]:
import numpy as np
e = np.around ( 1.5 , 0 )
print(e)

2.0


In [8]:
import numpy as np
d = np.around ( 2.5 , 0 )
print(d)

2.0


In [9]:
import numpy as np
e = np.around ( 6.084 , 2 )
print(e)

6.08


In [10]:
import numpy as np
f = np.around ( 7.744 , 2 )
print(f)

7.74


In [11]:
# floor() ROUNDS OFF THE DECIMALS TO THE LOWER INTEGER .
# USING floor() FUNCTION .

import numpy as np
xyz = np.floor ([ -8.836 , -5.184 , -4.5 , -3.5 , 1.5 , 2.5 , 6.084 , 7.744 ])
print(xyz)

[-9. -6. -5. -4.  1.  2.  6.  7.]


In [12]:
# ceil() ROUNDS OFF THE DECIMALS TO THE UPPER INTEGER .
# USING ceil() FUNCTION .

import numpy as np
xyz = np.ceil ([ -8.836 , -5.184 , -4.5 , -3.5 , 1.5 , 2.5 , 6.084 , 7.744 ])
print(xyz)

[-8. -5. -4. -3.  2.  3.  7.  8.]
