In [1]:
# SET : IT IS A COLLECTION OF UNIQUE ELEMENTS .
# unique() IS USED TO FIND A SET WITH UNIQUE ELEMENTS FROM ANY ARRAY .
# unique() ALSO CONVERTS THE ARRAY WITH REPEATED ELEMENTS TO A SET .

import numpy as np
a = np.array([6,1,4,3,5,2,4,3,2,1,6,5,2,4,6,5,1,3])
xyz = np.unique(a)
print(xyz)

[1 2 3 4 5 6]


In [2]:
# union1d() IS USED TO FIND THE UNIQUE VALUES OF 2 ONE DIMENSIONAL ARRAY .

import numpy as np
b = np.array([22,24,26,28,30,32,34,36])
c = np.array([30,32,34,36,38,40,42,44])
xyz = np.union1d(b,c)
print(xyz)

[22 24 26 28 30 32 34 36 38 40 42 44]


In [3]:
# intersection1d() IS USED TO FIND THE ONLY VALUES OR ELEMENTS THAT ARE PRESENT IN BOTH ONE DIMENSIONAL ARRAYS .

import numpy as np
b = np.array([22,24,26,28,30,32,34,36])
c = np.array([30,32,34,36,38,40,42,44])
xyz = np.intersect1d(b,c)
print(xyz)

[30 32 34 36]


In [4]:
import numpy as np
b = np.array([22,24,26,28,30,32,34,36])
c = np.array([30,32,34,36,38,40,42,44])
xyz = np.intersect1d ( b , c , assume_unique=True )
print(xyz)

[30 32 34 36]


In [5]:
# setdiff1d() IS USED TO FIND THE VALUES THAT ARE PRESENT IN 1ST SET BUT NOT PRESENT IN 2ND SET .

import numpy as np
b = np.array([22,24,26,28,30,32,34,36])
c = np.array([30,32,34,36,38,40,42,44])
xyz = np.setdiff1d ( b , c , assume_unique=True )
print(xyz)

[22 24 26 28]


In [6]:
# setdiff1d() IS USED TO FIND THE VALUES THAT ARE PRESENT IN 2ND SET BUT NOT PRESENT IN 1ST SET .

import numpy as np
b = np.array([22,24,26,28,30,32,34,36])
c = np.array([30,32,34,36,38,40,42,44])
xyz = np.setdiff1d ( c , b , assume_unique=True )
print(xyz)

[38 40 42 44]


In [7]:
# setxor1d() IS USED TO FIND THE VALUES THAT ARE NOT PRESENT IN BOTH ONE DIMENSIONAL ARRAYS .

import numpy as np
b = np.array([22,24,26,28,30,32,34,36])
c = np.array([30,32,34,36,38,40,42,44])
xyz = np.setxor1d ( b , c , assume_unique=True )
print(xyz)

[22 24 26 28 38 40 42 44]
