In [1]:
'''
TRIGONOMETRIC FUNCTIONS : NUMPY PROVIDES THE ufunc() LIKE sin() , cos() , tan() THAT TAKES VALUES IN RADIANS 
AND PRODUCE THE CORRESPONDING sin() , cos() , tan() VALUES .
'''

# FIND SIN VALUE OF pi/2 .

import numpy as np
a1 = np.sin(np.pi/2)
print(a1)

1.0


In [2]:
# FIND COS VALUE OF pi/2 .

import numpy as np
a2 = np.cos(np.pi/2)
print(a2)

6.123233995736766e-17


In [3]:
# FIND TAN VALUE OF pi/2 .

import numpy as np
a3 = np.tan(np.pi/2)
print(a3)

1.633123935319537e+16


In [4]:
# FIND SIN VALUE OF AN ARRAY .

import numpy as np
b1 = np.array ([ np.pi/3 , np.pi/4 , np.pi/5 , np.pi/6 , np.pi/7 , np.pi/8 ])
xyz = np.sin(b1)
print(xyz)

[0.8660254  0.70710678 0.58778525 0.5        0.43388374 0.38268343]


In [5]:
# FIND COS VALUE OF AN ARRAY .

import numpy as np
b2 = np.array ([ np.pi/3 , np.pi/4 , np.pi/5 , np.pi/6 , np.pi/7 , np.pi/8 ])
xyz = np.cos(b2)
print(xyz)

[0.5        0.70710678 0.80901699 0.8660254  0.90096887 0.92387953]


In [6]:
# FIND TAN VALUE OF AN ARRAY .

import numpy as np
b3 = np.array ([ np.pi/3 , np.pi/4 , np.pi/5 , np.pi/6 , np.pi/7 , np.pi/8 ])
xyz = np.tan(b3)
print(xyz)

[1.73205081 1.         0.72654253 0.57735027 0.48157462 0.41421356]


In [7]:
# BY DEFAULT ALL THE TRIGONOMETRIC FUNCTIONS TAKES RADIAN AS PARAMETER .
# NOTE : RADIAN VALUE = pi/180 * DEGREE VALUE .

# deg2rad() CONVETRS ALL ARRAY VALUES INTO RADIAN .
# CONVERT ALL ARRAY VALUES TO RADIAN .

import numpy as np
c1 = np.array([60,120,180,240,300,360])
xyz = np.deg2rad(c1)
print(xyz)

[1.04719755 2.0943951  3.14159265 4.1887902  5.23598776 6.28318531]


In [8]:
# rad2deg() CONVETRS ALL ARRAY VALUES INTO DEGREE .
# CONVERT ALL ARRAY VALUES TO DEGREE .

import numpy as np
c2 = np.array ([ np.pi/3 , 2*np.pi/3 , np.pi , 4*np.pi/3 , 5*np.pi/3 , 2*np.pi ])
xyz = np.rad2deg(c2)
print(xyz)

[ 60. 120. 180. 240. 300. 360.]


In [9]:
import numpy as np
c2 = np.array ([ np.pi/3 , np.pi*2/3 , np.pi , np.pi*4/3 , np.pi*5/3 , np.pi*2 ])
xyz = np.rad2deg(c2)
print(xyz)

[ 60. 120. 180. 240. 300. 360.]


In [10]:
'''
NUMPY PROVIDES THE ANGLES OF arcsin() , arccos() , arctan() THAT TAKES VALUES IN RADIANS 
AND PRODUCE THE CORRESPONDING sin() , cos() , tan() VALUES .
'''

# FIND ARCSIN ANGLE OF 1.0 .

import numpy as np
d1 = np.arcsin(1.0)
print(d1)

1.5707963267948966


In [11]:
# FIND ARCCOS ANGLE OF 1.0 .

import numpy as np
d2 = np.arccos(1.0)
print(d2)

0.0


In [12]:
# FIND ARCTAN ANGLE OF 1.0 .

import numpy as np
d3 = np.arctan(1.0)
print(d3)

0.7853981633974483


In [13]:
# FIND ARCSIN ANGLE OF AN ARRAY .

import numpy as np
e1 = np.array ([ -1.0 , -0.1 , 0.0 , 0.1 , 1.0 ])
xyz = np.arcsin(e1)
print(xyz)

[-1.57079633 -0.10016742  0.          0.10016742  1.57079633]


In [14]:
# FIND ARCCOS ANGLE OF AN ARRAY .

import numpy as np
e2 = np.array ([ -1.0 , -0.1 , 0.0 , 0.1 , 1.0 ])
xyz = np.arccos(e2)
print(xyz)

[3.14159265 1.67096375 1.57079633 1.47062891 0.        ]


In [15]:
# FIND ARCTAN ANGLE OF AN ARRAY .

import numpy as np
e3 = np.array ([ -1.0 , -0.1 , 0.0 , 0.1 , 1.0 ])
xyz = np.arctan(e3)
print(xyz)

[-0.78539816 -0.09966865  0.          0.09966865  0.78539816]


In [16]:
# HYPOTENUSE CAN BE CALCUALTED BY USING PYTHAGORAS THEOREM IN NUMPY .
# hypot() IS USED FOR FINDING THE HYPOTENUSE 
# hypot() TAKES VALUES IN RADIANS AND PRODUCE THE CORRESPONDING sin() , cos() , tan() VALUES .

import numpy as np
f1 = 8
f2 = 6
xyz = np.hypot(f1,f2)
print(xyz)

10.0


In [17]:
import numpy as np
f3 = 12
f4 = 5
xyz = np.hypot(f3,f4)
print(xyz)

13.0


In [18]:
import numpy as np
f5 = 9
f6 = 7
xyz = np.hypot(f5,f6)
print(xyz)

11.40175425099138
